- hosts: all
  become: true
  become_method: sudo

  vars_files:
    - defaults/main.yml
    - vars/main.yml

  tasks:

    - import_tasks: tasks/preflight.yml
      tags:
      - node_exporter_install
      - node_exporter_configure
      - node_exporter_run

    - import_tasks: tasks/install.yml
      become: true
      when:
        ( not __node_exporter_is_installed.stat.exists ) or
        ( (__node_exporter_current_version_output.stderr_lines | length > 0) and (__node_exporter_current_version_output.stderr_lines[0].split(" ")[2] != node_exporter_version) ) or
        ( (__node_exporter_current_version_output.stdout_lines | length > 0) and (__node_exporter_current_version_output.stdout_lines[0].split(" ")[2] != node_exporter_version) ) or
        ( node_exporter_binary_local_dir | length > 0 )
      tags:
        - node_exporter_install
      
    - import_tasks: tasks/selinux.yml
      become: true
      when: ansible_selinux.status == "enabled"
      tags:
        - node_exporter_configure

    - import_tasks: tasks/configure.yml
      become: true
      tags:
        - node_exporter_configure

    - name: Ensure Node Exporter is enabled on boot
      become: true
      systemd:
        daemon_reload: true
        name: node_exporter
        enabled: true
        state: started
      when:
        - not ansible_check_mode
      tags:
        - node_exporter_run

    - name: Do permit traffic in default zone for 'node_exporter' on port 9100/tcp
      firewalld:
        port: 9100/tcp
        permanent: yes
        state: enabled
      notify: reload service firewalld

  handlers:
    # - include_tasks: main.yml
    - name: restart node_exporter
      become: true
      systemd:
        daemon_reload: true
        name: node_exporter
        state: restarted
      when:
        - not ansible_check_mode
    
    - name: reload service firewalld
      systemd:
        name: firewalld
        state: reloaded
