---
- name: restart node_exporter
  become: true
  systemd:
    daemon_reload: true
    name: node_exporter
    state: restarted
  when:
    - not ansible_check_mode

- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded
